# Melos configuration for JeepneyGo monorepo
# See: https://melos.invertase.dev/

name: jeepneygo

packages:
  - apps/*
  - packages/*

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  # Analyze all packages
  analyze:
    run: melos exec -- flutter analyze
    description: Run flutter analyze in all packages

  # Format all packages
  format:
    run: melos exec -- dart format .
    description: Format all packages

  # Run tests
  test:
    run: melos exec -- flutter test
    description: Run tests in all packages
    packageFilters:
      dirExists: test

  # Build runner for code generation
  build_runner:
    run: melos exec -- flutter pub run build_runner build --delete-conflicting-outputs
    description: Run build_runner in packages that use it
    packageFilters:
      dependsOn: build_runner

  # Clean all packages
  clean:
    run: melos exec -- flutter clean
    description: Clean all packages

  # Get dependencies
  get:
    run: melos exec -- flutter pub get
    description: Get dependencies for all packages

  # Upgrade dependencies
  upgrade:
    run: melos exec -- flutter pub upgrade
    description: Upgrade dependencies for all packages

  # Run driver app (web)
  run:driver:
    run: cd apps/driver_app && flutter run -d chrome
    description: Run the Driver app on web

  # Run commuter app (web)
  run:commuter:
    run: cd apps/commuter_app && flutter run -d chrome
    description: Run the Commuter app on web

  # Run admin dashboard (web)
  run:admin:
    run: cd apps/admin_dashboard && flutter run -d chrome
    description: Run the Admin dashboard on web

  # Build all web apps
  build:web:all:
    run: |
      cd apps/driver_app && flutter build web --release
      cd ../commuter_app && flutter build web --release
      cd ../admin_dashboard && flutter build web --release
    description: Build all web apps for production

  # Build driver web
  build:web:driver:
    run: cd apps/driver_app && flutter build web --release
    description: Build Driver app for web

  # Build commuter web
  build:web:commuter:
    run: cd apps/commuter_app && flutter build web --release
    description: Build Commuter app for web

  # Build admin web
  build:web:admin:
    run: cd apps/admin_dashboard && flutter build web --release
    description: Build Admin dashboard for web

  # Serve driver app locally
  serve:driver:
    run: cd apps/driver_app && flutter run -d web-server --web-port=8080
    description: Serve Driver app on localhost:8080

  # Serve commuter app locally
  serve:commuter:
    run: cd apps/commuter_app && flutter run -d web-server --web-port=8081
    description: Serve Commuter app on localhost:8081

  # Serve admin dashboard locally
  serve:admin:
    run: cd apps/admin_dashboard && flutter run -d web-server --web-port=8082
    description: Serve Admin dashboard on localhost:8082

  # Build iOS (archived - requires Mac)
  build:ios:
    run: melos exec --scope="driver_app" --scope="commuter_app" -- flutter build ios --release
    description: Build iOS release for mobile apps

  # Build Android
  build:android:
    run: melos exec --scope="driver_app" --scope="commuter_app" -- flutter build apk --release
    description: Build Android APK for mobile apps
