// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfZ97X_2Y7Bgc1fUiNq0Zc7ufs1U37lEs',
    appId: '1:365633927642:web:3f3cef80b244bf85f0e8e3',
    messagingSenderId: '365633927642',
    projectId: 'jeepneygo-d3118',
    authDomain: 'jeepneygo-d3118.firebaseapp.com',
    storageBucket: 'jeepneygo-d3118.firebasestorage.app',
    measurementId: 'G-0H5R00BNK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDreef8wnGuD5A5sdVZPrHcvaBixipqVd4',
    appId: '1:365633927642:android:6aa20d72015b7e7bf0e8e3',
    messagingSenderId: '365633927642',
    projectId: 'jeepneygo-d3118',
    storageBucket: 'jeepneygo-d3118.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDarits2LqRVNXawRDCrPIQmG8WjBi0yEM',
    appId: '1:365633927642:ios:1900421e29be249bf0e8e3',
    messagingSenderId: '365633927642',
    projectId: 'jeepneygo-d3118',
    storageBucket: 'jeepneygo-d3118.firebasestorage.app',
    iosBundleId: 'com.jeepneygo.commuterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfZ97X_2Y7Bgc1fUiNq0Zc7ufs1U37lEs',
    appId: '1:365633927642:web:c47dbf260d7710e0f0e8e3',
    messagingSenderId: '365633927642',
    projectId: 'jeepneygo-d3118',
    authDomain: 'jeepneygo-d3118.firebaseapp.com',
    storageBucket: 'jeepneygo-d3118.firebasestorage.app',
    measurementId: 'G-8MMJVR9WMR',
  );
}
